### ISSUE TITLE
Values show up alright in the BLE monitor, but don't carry over to the plant component

### ISSUE THREAD

**Issue by nschloe** [Olen/homeassistant-plant#118]
The is what I see in the BLE monitor:

![screenshot_2023-12-12-172534](https://github.com/Olen/homeassistant-plant/assets/181628/dd93ab5b-15ea-4a28-9caf-a01f01005d93)

This is what I see in the corresponding plant device:

![screenshot_2023-12-12-172455](https://github.com/Olen/homeassistant-plant/assets/181628/2b308e9e-302c-438a-89c5-c780cb5ad5da)

No idea why it doesn't carry over. Is there a way to "reset" the connection?

**Comment by Olen** [comment]
What does the attributes in the plant sensor show?  It should show the source sensor.

You can use the service call to "replace" the source sensors.

```
service: plant.replace_sensor
data:
  meter_entity: sensor.rose_illumination
  new_sensor: sensor.ble_sensor_12_illumination
```
