### ISSUE TITLE
Low light still results in problem with "warn_low_brightness: false"

### ISSUE THREAD

**Issue by olskar** [Olen/homeassistant-plant#12]
WIth below yaml, low light still results in problem

```
1:
  species: dypsis lutescens
  name: Guldpalm
  warn_low_brightness: false
  sensors:
    moisture: sensor.xiaomi_1_moisture
    battery: sensor.xiaomi_1_battery_level
    temperature: sensor.xiaomi_1_temperature
    conductivity: sensor.xiaomi_1_soil_conductivity
    brightness: sensor.xiaomi_1_illuminance
```

![image](https://user-images.githubusercontent.com/18314560/139642391-801f95a1-8f50-4073-b715-cba6e84b8bc8.png)
