### ISSUE TITLE
Feature Request: Allow Template For Battery Entity

### ISSUE THREAD

**Issue by Colorado4Wheeler** [Olen/homeassistant-plant#165]
I would love to be able to template the battery entity.  I use this with auto entities and it works great, allowing me to filter the results as needed, but I can't display the battery percentage because the battery entity won't allow a template, i.e.:

```
    - type: custom:flower-card
      entity: plant.ecowitt_outdoor_1_ch1
      show_bars:
        - temperature
        - humidity
        - moisture
      display_type: full
      battery_sensor: >-
        {{ sensor.outdoor_1_ch1_battery_level }}
```

Obviously the above would be a single line but I used that example just to show my request.  My actual use case is a much more complex template that extracts the entity name to re-assemble the battery entity name.

**Comment by Olen** [comment]
Please provide a PR.
For now, I have a problem understanding the use case.  Why would a template be needed to just add a simple entity_id?
 
Maybe you can use something like this?
https://github.com/iantrich/config-template-card
(No idea if it works or is still maintained, it was just something that showed up on a google search)

**Comment by Colorado4Wheeler** [comment]
When configuring manually providing the entity_id is fine, works great, but if you use something like [Auto Entities](https://github.com/thomasloven/lovelace-auto-entities) there is no way to populate the battery field since it's not part of the plant entity itself.  My request is so that I can template the proper value into that field when it is auto generated.

**Comment by Colorado4Wheeler** [comment]
My mistake, this should have been on the flower card - although, if we are using Home Assistant's built-in Plant system as a base for this replacement, the HA plant does have the ability to link to a battery entity on the plant template itself, which should then translate to the Flower Card.

**Comment by Olen** [comment]
I am pretty sure my flower-card does not work with the standard HA-plant-integration.

I have - on purpose - not added a battery entity to the plant device, as for many of my plants, I use different physical sensors for e.g temperature, humidity, light etc.  Any of these (can) have batteries, so I don't like to include a single battery to the plant as I want the plant to be an autonomous entity and plants themselves do not usually have batteries...

Regarding templating of the card config, I have no idea how to attack that, so I would really need help there.

**Comment by marefr** [comment]
I  think I've  solved what your asking for using the auto entities.  Works for me at least. 

Dashboard example (each card is an area, Vardagsrum (living room) in this example):
```yaml
views:
  - title: Home
    cards:
      - square: false
        type: grid
        title: Vardagsrum
        cards:
          - type: custom:auto-entities
            filter:
              template: |-
                {% for state in states.plant -%}
                  {%- if state.entity_id | regex_match("plant.plant.*", ignorecase=True) and area_id(state.entity_id) == 'vardagsrum' -%}
                    {{
                      {
                        'entity': state.entity_id,
                        'type': 'custom:flower-card',
                        'battery_sensor': state.entity_id | regex_replace(find='plant\\.plant\\_([\\d]+)', replace='sensor.mi_flora_\\1_battery', ignorecase=False),
                        'show_bars': [
                          'moisture',
                          'conductivity',
                          'temperature',
                          'illuminance',
                          'humidity',
                          'dli'
                        ],
                        'display_type': 'full'
                      }
                    }},
                  {%- endif -%}
                {%- endfor %}
            columns: 1
            sort:
              method: friendly_name
            show_empty: true
            card_param: cards
            card:
              square: false
              type: grid
              columns: 1
```

**Comment by Olen** [comment]
This probably belongs under the flower-card.

If someone can verify that the example works, I can add it to the README there.

**Comment by marefr** [comment]
See below for verification it works. I should have added earlier that I use a naming scheme for plants and the devices I use for measuring (Mi Flora), so the example provided earlier requires plants named `plant.plant_001`... `plant.plant_XYZ` and devices named `sensor.mi_flora_001`... `sensor.mi_flora_XYZ`. The key is using the same identifier of some kind (001) for plant and sensor that has the battery and the example should be able to be tailored for your plants and sensors. 

![IMG_4607](https://github.com/Olen/homeassistant-plant/assets/1668778/94ec5d0d-f66c-4005-b312-a589e71231dd)
![IMG_4608](https://github.com/Olen/homeassistant-plant/assets/1668778/14bc2921-b255-47f4-a0dc-52560d8cb8c1)
![IMG_4609](https://github.com/Olen/homeassistant-plant/assets/1668778/0b684684-dca1-48fc-8f32-0ec10e16fb4c)

**Comment by Olen** [comment]
Would you be able to simplify the config to show it with just one card (e.g. without the auto-entities)?

That way I can add examples for both a single card, and for auto-entites (unless auto-entities is a prerequisite for the battery-template to work).

**Comment by marefr** [comment]
A single card with static config?

```yaml
type: custom:flower-card
entity: plant.plant_001
battery_sensor: sensor.mi_flora_001_battery
show_bars:
  - moisture
  - conductivity
  - temperature
  - illuminance
  - humidity
  - dli
```
