### ISSUE TITLE
Daily Light Integral

### ISSUE THREAD

**Issue by ACrazyConcept** [Olen/homeassistant-plant#21]
Would it be relevant to add Daily Light Integral as a sensor?

Ref.: https://community.home-assistant.io/t/light-accumulation-for-xiaomi-flower-sensor/111180/26

**Comment by slaxor505** [comment]
Yeah, we definitely need accumulated light value to monitor and maintain a healthy environment.

**Comment by Olen** [comment]
I looked at that, and it looks lite quite heavy calculations including lookups in a few tables and the need to know what kind of light each plant is subject to etc. for a very inaccurate result (see the last two posts).

But on the other hand, we are currently just checking if the _highest_ measured value for the last 3 days (by default) is above the configured minimum - which is maybe a little to simple again.
If you have an idea of a better thing to report on, which does not require to much work to add, I can look into it.

**Comment by ACrazyConcept** [comment]
@Olen
Yeah I agree it is not that straight forward to calculate the actual DLI value. And maybe most people aren't tracking their plants to this level in ha anyway. So I totally get if this is too niche to want to add at all :)
But how about just to add it as a config option. Then leave it up to the user whether they create their own calculated sensors or in case they have a proper quantum sensor hooked up use that.
Then the plant component could have a similar min/max setting and perhaps something similar to the check_days for brightness. Although it might need to be handled slightly differently due to being an accumulated value.

```
    sensors:
      moisture: sensor.mi_m_80eaca88xxxx
      conductivity: sensor.mi_c_80eaca88xxxx
      temperature: sensor.mi_t_80eaca88xxxx
      brightness: sensor.mi_l_80eaca88xxxx
      light_integral: sensor.light_integral
```
