### ISSUE TITLE
Zigbee Soil Sensor not identified

### ISSUE THREAD

**Issue by mamostacero** [Olen/homeassistant-plant#237]
I have a Soil Sensor Giex GX-04 integrated via TUYA in Home Assistant and I can see the temperature, humidity and battery level sensors

When I create a new plant I can choose the correct temepratrure sensor but I can't select none humidity sensor: "No matching entities found"  and I have not only these humidity sensor integtrated in Home assistant.... I have a bunch working all well,

**Comment by el** [comment]
You can create a helper like this in your `configuration.yaml`:

```
template:
  - sensor:
      - name: "Soil Moisture" # Choose your desired friendly name
        unique_id: "soil_sensor_moisture" # Make this unique
        state: "{{ states('sensor.soil_sensor_soil_moisture') }}" # Get the state from your zigbee sensor
        unit_of_measurement: "%" # Or your desired unit
        device_class: "moisture" # This will give it the appropriate icon and state representation
```
