### ISSUE TITLE
KeyError: 'species' during migration

### ISSUE THREAD

**Issue by thoemy** [Olen/homeassistant-plant#30]
After updating from Version 1.0.0 to Version 2.0.0-beta2 I get the following error.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/plant/__init__.py", line 115, in async_setup
    await async_migrate_plant(hass, plant, config[DOMAIN][plant])
  File "/config/custom_components/plant/__init__.py", line 136, in async_migrate_plant
    plant_config = await plant_helper.generate_configentry(config=config)
  File "/config/custom_components/plant/plant_helpers.py", line 174, in generate_configentry
    jpeg_exists = cv.isfile(f"{DEFAULT_IMAGE_PATH}{config[ATTR_SPECIES]}.jpg")
KeyError: 'species'
```

My `configuration.yml`.

```yaml
plant:
  openplantbook:
    client_id: abc123
    secret: abc123

  plant_couch:
    species: "spathiphyllum 'coco cupido'"
    image: openplantbook
    sensors:
      moisture: sensor.p1m
      conductivity: sensor.p1c
      temperature: sensor.p1t
      brightness: sensor.p1i

  plant_gluecksfeder:
    species: "zamioculcas zamiifolia"
    image: openplantbook
    sensors:
      moisture: sensor.p2m
      conductivity: sensor.p2c
      temperature: sensor.p2t
      brightness: sensor.p2i

  plant3:
    species: "ficus elastica"
    image: openplantbook
    sensors:
      moisture: sensor.p3m
      conductivity: sensor.p3c
      temperature: sensor.p3t
      brightness: sensor.p3i

  plant4:
    species: "monstera deliciosa"
    image: openplantbook
    sensors:
      moisture: sensor.p4m
      conductivity: sensor.p4c
      temperature: sensor.p4t
      brightness: sensor.p4i

  plant5:
    species: "dracaena deremensis 'warneckii'"
    image: openplantbook
    sensors:
      moisture: sensor.p5m
      conductivity: sensor.p5c
      temperature: sensor.p5t
      brightness: sensor.p5i

  plant6:
    species: "bambusa multiplex"
    image: openplantbook
    sensors:
      moisture: sensor.p6m
      conductivity: sensor.p6c
      temperature: sensor.p6t
      brightness: sensor.p6i

  # Goldene Efefute
  plant7:
    species: "epipremnum aureum"
    image: openplantbook
    sensors:
      moisture: sensor.p7m
      conductivity: sensor.p7c
      temperature: sensor.p7t
      brightness: sensor.p7i

  plant8:
    species: "ficus microcarpa bonsai"
    image: openplantbook
    sensors:
      moisture: sensor.p8m
      conductivity: sensor.p8c
      temperature: sensor.p8t
      brightness: sensor.p8i

  plant9_2:
    #species: "zamioculcas zamiifolia" # plant9: Glücksfeder Schlafzimmer
    #species: "ficus elastica" # plant9-1: Gummibaum Gang
    species: "euphorbia leuconeura"
    image: openplantbook
    sensors:
      moisture: sensor.p9m
      conductivity: sensor.p9c
      temperature: sensor.p9t
      brightness: sensor.p9i
```
