### ISSUE TITLE
All plants imported as "unnamed entry"

### ISSUE THREAD

**Issue by syphernl** [Olen/homeassistant-plant#33]
With [v2.0.0-beta.12](https://github.com/Olen/homeassistant-plant/tree/v2.0.0-beta.12) all of my plants are imported as "Unnamed entry" with "none" as name, which gets used in the entity generation, e.g.

* `sensor.none_air_humidity`
* `sensor.none_illuminance_2`

They were all in the yaml with configs like:

```
plant:
  dracaena_marginata:
    sensors:
      moisture: sensor.livingroom_dracaena_marginata_moisture
      temperature: sensor.livingroom_dracaena_marginata_temperature
      conductivity: sensor.livingroom_dracaena_marginata_soil_conductivity
      brightness: sensor.livingroom_dracaena_marginata_illuminance
    min_moisture: 20
    max_moisture: 60
    min_conductivity: 500
    min_temperature: 15
```

**Comment by Olen** [comment]
You are missing the 'name' parameter in the config.
Just delete them all from the ui, add name to the config entries and restart HA to do a new migration.

**Comment by Olen** [comment]
(or you can just change the device name and check the box to update then entity ids)

**Comment by syphernl** [comment]
> You are missing the 'name' parameter in the config. Just delete them all from the ui, add name to the config entries and restart HA to do a new migration.

Ah! I'm migrating from "vanilla" HASS plant integration straight to V2. That's why I didn't have a `name` parameter. I will try if that helps.

**Comment by syphernl** [comment]
Even with a `name` and `species` entries it keeps showing up as unnamed.

```
plant:
  office_euphorbia:
    name: Office Euphorbia
    species: Euphorbia Trigona
    sensors:
      moisture: sensor.office_euphorbia_moisture
      temperature: sensor.office_euphorbia_temperature
      conductivity: sensor.office_euphorbia_soil_conductivity
      brightness: sensor.office_euphorbia_illuminance
    min_moisture: 20
    max_moisture: 60
    min_conductivity: 500
    min_temperature: 15
```

> (or you can just change the device name and check the box to update then entity ids)

Unfortunately all entities contain `none` have no info of the plants either so there is no way knowing which is which.
