### ISSUE TITLE
not syncing plant

### ISSUE THREAD

**Issue by warlordattack** [Olen/homeassistant-plant#35]
hello i have 3 mi flower plants

Xiaomi BLE gives data for all 3 plants, 
but plant monitor do not give data for one of them : pl-rosa-marie
(this plant is on the balcony far from bluetooth reciever, but it gives data sometimes in Xiaomi BLE, but never in Plant Monitor)

how can i debug this please ?

Xiaomi BLE : OK
````
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: sensor.fl_dischidia_conductivity
        name: Conductivity
      - entity: sensor.fl_dischidia_illuminance
        name: Illuminance
      - entity: sensor.fl_dischidia_moisture
        name: Moisture
      - entity: sensor.fl_dischidia_temperature_2
        name: Temperature
    title: fl-dischidia
    state_color: true
  - type: entities
    entities:
      - entity: sensor.fl_rhipsalis_conductivity_2
        name: Conductivity
      - entity: sensor.fl_rhipsalis_illuminance_2
        name: Illuminance
      - entity: sensor.fl_rhipsalis_moisture_2
        name: Moisture
      - entity: sensor.fl_rhipsalis_temperature
        name: Temperature
    title: fl-rhipsalis
    state_color: true
  - type: entities
    entities:
      - sensor.fl_rosa_marie_illuminance
      - sensor.fl_rosa_marie_moisture
      - sensor.fl_rosa_marie_temperature
      - sensor.fl_rosa_marie_conductivity
    title: fl-rosa-marie
    state_color: true
````

Plant Monitor  : NOK
````
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: sensor.pl_dischidia_air_humidity
        name: Air humidity
      - entity: sensor.pl_dischidia_conductivity
        name: Conductivity
      - entity: sensor.pl_dischidia_dli
        name: Dli
      - entity: sensor.pl_dischidia_illuminance
        name: Illuminance
      - entity: sensor.pl_dischidia_soil_moisture
        name: Soil moisture
      - entity: sensor.pl_dischidia_temperature
        name: Temperature
    title: pl-dischidia
  - type: entities
    entities:
      - entity: sensor.pl_rhipsalis_air_humidity
        name: Air humidity
      - entity: sensor.pl_rhipsalis_conductivity
        name: Conductivity
      - entity: sensor.pl_rhipsalis_dli
        name: Dli
      - entity: sensor.pl_rhipsalis_illuminance
        name: Illuminance
      - entity: sensor.pl_rhipsalis_soil_moisture
        name: Soil moisture
      - entity: sensor.pl_rhipsalis_temperature
        name: Temperature
    title: pl-rhipsalis
  - type: entities
    entities:
      - entity: sensor.pl_rosa_marie_air_humidity
        name: Air humidity
      - entity: sensor.pl_rosa_marie_conductivity
        name: Conductivity
      - entity: sensor.pl_rosa_marie_dli
        name: Dli
      - entity: sensor.pl_rosa_marie_illuminance
        name: Illuminance
      - entity: sensor.pl_rosa_marie_soil_moisture
        name: Soil moisture
      - entity: sensor.pl_rosa_marie_temperature
        name: Temperature
    title: pl-rosa-marie
````
![2022-08-17_102600](https://user-images.githubusercontent.com/3226486/185073716-fffa4908-22fa-435f-b5ac-0fdcdacd43a3.png)
![2022-08-17_102617](https://user-images.githubusercontent.com/3226486/185073721-93c4ef4b-70bd-4dd7-bc96-2aca792d1d5f.png)
![2022-08-17_102807](https://user-images.githubusercontent.com/3226486/185073725-9ab9d8a6-dac2-4dcc-89d6-f1cf4964623b.png)
![2022-08-17_103430](https://user-images.githubusercontent.com/3226486/185073728-86e5f11a-bd56-4fb4-8647-a688241fb0a2.png)
